version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:9.6.10
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: deepuai
      POSTGRES_PASSWORD: deepuai
    volumes:
          - database:/var/lib/postgresql/data

volumes:
  database: